// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.24;

import "@openzeppelin/contracts-upgradeable/access/AccessControlUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";

/// @title ConstitutionalCompliance
/// @notice ChainLedger Phase 5 — Constitutional compliance monitor.
///         Every fund release is checked against encoded constitutional provisions
///         before commitment. Implements the Auto-FIR generation module and
///         Lokpal integration feed from the ChainLedger Implementation Plan.
///
/// @dev    Encodes Article 275/282 rules, Finance Commission award limits,
///         FRBM Act fiscal deficit thresholds, and auto-escalation timelines.
contract ConstitutionalCompliance is AccessControlUpgradeable, UUPSUpgradeable {
    bytes32 public constant ADMIN_ROLE = keccak256("ADMIN_ROLE");
    bytes32 public constant CAG_ROLE = keccak256("CAG_ROLE");
    bytes32 public constant UPGRADER_ROLE = keccak256("UPGRADER_ROLE");

    // ─── Types ───────────────────────────────────────────────────────────

    enum Severity { LOW, MEDIUM, HIGH, CRITICAL }
    enum FIRStatus { Pending, AutoGenerated, SubmittedToPolice, CourtFiled }

    struct ComplianceRule {
        bytes32 ruleId;
        string description;     // e.g., "Article 275 — Grants to States"
        string legalBasis;      // e.g., "Constitution of India, Article 275"
        bool active;
    }

    struct ComplianceViolation {
        bytes32 violationId;
        bytes32 disbursementId;
        bytes32 ruleId;
        Severity severity;
        string details;
        uint64 detectedAt;
        bool resolved;
    }

    struct AutoFIR {
        bytes32 firId;
        bytes32 disbursementId;
        bytes32 accusedDid;          // DID of official who authorized the txn
        uint256 amount;              // disputed amount
        Severity severity;
        string ipcSections;          // "IPC 409, 420; Prevention of Corruption Act S.13"
        string evidenceBlockHash;    // block hash containing the evidence
        FIRStatus status;
        uint64 generatedAt;
        uint64 escalationDeadline;   // 72 hours after CAG notification
    }

    // ─── Storage ─────────────────────────────────────────────────────────
    mapping(bytes32 => ComplianceRule) public rules;
    bytes32[] public ruleIds;

    mapping(bytes32 => ComplianceViolation) public violations;
    bytes32[] public violationIds;

    mapping(bytes32 => AutoFIR) public autoFIRs;
    bytes32[] public firIds;
    uint256 public firCount;

    // Lokpal feed: disbursementId => pushed to Lokpal
    mapping(bytes32 => bool) public lokpalNotified;

    uint256 public constant ESCALATION_WINDOW = 72 hours;

    // ─── Events ──────────────────────────────────────────────────────────
    event RuleRegistered(bytes32 indexed ruleId, string description);
    event ViolationDetected(bytes32 indexed violationId, bytes32 indexed disbursementId, Severity severity);
    event AutoFIRGenerated(bytes32 indexed firId, bytes32 indexed disbursementId, bytes32 accusedDid);
    event LokpalNotified(bytes32 indexed disbursementId, Severity severity);
    event FIRStatusUpdated(bytes32 indexed firId, FIRStatus newStatus);

    // ─── Errors ──────────────────────────────────────────────────────────
    error RuleNotFound(bytes32 ruleId);
    error FIRNotFound(bytes32 firId);
    error EscalationWindowNotExpired();

    // ─── Initializer ─────────────────────────────────────────────────────
    function initialize(address _admin) external initializer {
        __AccessControl_init();
        __UUPSUpgradeable_init();

        _grantRole(DEFAULT_ADMIN_ROLE, _admin);
        _grantRole(ADMIN_ROLE, _admin);
        _grantRole(CAG_ROLE, _admin);
        _grantRole(UPGRADER_ROLE, _admin);

        // Pre-register core constitutional rules
        _registerRule("Article 275 — Grants to States", "Constitution of India, Article 275");
        _registerRule("Article 282 — Expenditure from CFI", "Constitution of India, Article 282");
        _registerRule("FRBM Act — Fiscal Deficit Limit", "Fiscal Responsibility and Budget Management Act, 2003");
        _registerRule("Finance Commission Award Ceiling", "15th/16th Finance Commission");
        _registerRule("Article 293 — State Borrowing Limits", "Constitution of India, Article 293");
    }

    // ─── Rule Management ─────────────────────────────────────────────────

    function registerRule(string calldata _description, string calldata _legalBasis)
        external onlyRole(ADMIN_ROLE) returns (bytes32 ruleId)
    {
        return _registerRule(_description, _legalBasis);
    }

    // ─── Violation Recording ─────────────────────────────────────────────

    /// @notice Record a constitutional compliance violation.
    function recordViolation(
        bytes32 _disbursementId,
        bytes32 _ruleId,
        Severity _severity,
        string calldata _details
    ) external onlyRole(CAG_ROLE) returns (bytes32 violationId) {
        if (!rules[_ruleId].active) revert RuleNotFound(_ruleId);

        violationId = keccak256(abi.encodePacked(_disbursementId, _ruleId, block.timestamp));

        violations[violationId] = ComplianceViolation({
            violationId: violationId,
            disbursementId: _disbursementId,
            ruleId: _ruleId,
            severity: _severity,
            details: _details,
            detectedAt: uint64(block.timestamp),
            resolved: false
        });
        violationIds.push(violationId);

        emit ViolationDetected(violationId, _disbursementId, _severity);

        // Auto-notify Lokpal for HIGH and CRITICAL
        if (_severity == Severity.HIGH || _severity == Severity.CRITICAL) {
            lokpalNotified[_disbursementId] = true;
            emit LokpalNotified(_disbursementId, _severity);
        }
    }

    // ─── Auto-FIR Generation (Phase 5 §4.18) ────────────────────────────

    /// @notice Generate an Auto-FIR when anomaly score crosses CRITICAL and
    ///         remains unresolved for 72 hours after CAG notification.
    function generateAutoFIR(
        bytes32 _disbursementId,
        bytes32 _accusedDid,
        uint256 _amount,
        string calldata _ipcSections,
        string calldata _evidenceBlockHash
    ) external onlyRole(CAG_ROLE) returns (bytes32 firId) {
        firId = keccak256(abi.encodePacked(_disbursementId, _accusedDid, block.timestamp));

        autoFIRs[firId] = AutoFIR({
            firId: firId,
            disbursementId: _disbursementId,
            accusedDid: _accusedDid,
            amount: _amount,
            severity: Severity.CRITICAL,
            ipcSections: _ipcSections,
            evidenceBlockHash: _evidenceBlockHash,
            status: FIRStatus.AutoGenerated,
            generatedAt: uint64(block.timestamp),
            escalationDeadline: uint64(block.timestamp + ESCALATION_WINDOW)
        });
        firIds.push(firId);
        firCount++;

        emit AutoFIRGenerated(firId, _disbursementId, _accusedDid);
    }

    /// @notice Update FIR status (CAG tracks progression).
    function updateFIRStatus(bytes32 _firId, FIRStatus _newStatus) external onlyRole(CAG_ROLE) {
        AutoFIR storage fir = autoFIRs[_firId];
        if (fir.generatedAt == 0) revert FIRNotFound(_firId);
        fir.status = _newStatus;
        emit FIRStatusUpdated(_firId, _newStatus);
    }

    /// @notice Auto-escalate an FIR after the 72-hour window expires.
    /// @dev Enforces the escalation deadline that was previously stored but never checked.
    ///      If the FIR is still AutoGenerated after 72 hours, it is auto-submitted to police.
    function triggerEscalation(bytes32 _firId) external onlyRole(CAG_ROLE) {
        AutoFIR storage fir = autoFIRs[_firId];
        if (fir.generatedAt == 0) revert FIRNotFound(_firId);
        require(fir.status == FIRStatus.AutoGenerated, "FIR already escalated");
        require(block.timestamp >= fir.escalationDeadline, "Escalation window not expired");
        fir.status = FIRStatus.SubmittedToPolice;
        emit FIRStatusUpdated(_firId, FIRStatus.SubmittedToPolice);
    }

    // ─── Views ───────────────────────────────────────────────────────────

    function getViolation(bytes32 _id) external view returns (ComplianceViolation memory) {
        return violations[_id];
    }

    function getFIR(bytes32 _id) external view returns (AutoFIR memory) {
        return autoFIRs[_id];
    }

    function getAllViolationIds() external view returns (bytes32[] memory) {
        return violationIds;
    }

    function getAllFIRIds() external view returns (bytes32[] memory) {
        return firIds;
    }

    // ─── Internal ────────────────────────────────────────────────────────

    function _registerRule(string memory _description, string memory _legalBasis)
        internal returns (bytes32 ruleId)
    {
        ruleId = keccak256(abi.encodePacked(_description, _legalBasis));
        rules[ruleId] = ComplianceRule({
            ruleId: ruleId,
            description: _description,
            legalBasis: _legalBasis,
            active: true
        });
        ruleIds.push(ruleId);
        emit RuleRegistered(ruleId, _description);
    }

    function _authorizeUpgrade(address) internal override onlyRole(UPGRADER_ROLE) {}
}
